image:
  file: .gitpod/Dockerfile
tasks:
  - name: Start Docker Daemon
    command: sudo docker-up &
  - before: "echo 'export PIP_USER=no' >> ~/.bashrc && export PIP_USER=no"
    name: Use Pulumi
    command: pulumi login
ports:
  - port: 3000
    onOpen: ignore
