# coding=utf-8
# *** WARNING: this file was generated by crd2pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union
from ... import _utilities, _tables
from . import outputs

__all__ = [
    'CertificateSpec',
    'CertificateSpecIssuerRef',
    'CertificateSpecKeystores',
    'CertificateSpecKeystoresJks',
    'CertificateSpecKeystoresJksPasswordSecretRef',
    'CertificateSpecKeystoresPkcs12',
    'CertificateSpecKeystoresPkcs12PasswordSecretRef',
    'CertificateSpecPrivateKey',
    'CertificateSpecSubject',
    'CertificateStatus',
    'CertificateStatusConditions',
]

@pulumi.output_type
class CertificateSpec(dict):
    """
    Desired state of the Certificate resource.
    """
    def __init__(__self__, *,
                 issuer_ref: 'outputs.CertificateSpecIssuerRef',
                 secret_name: str,
                 common_name: Optional[str] = None,
                 dns_names: Optional[Sequence[str]] = None,
                 duration: Optional[str] = None,
                 email_addresses: Optional[Sequence[str]] = None,
                 encode_usages_in_request: Optional[bool] = None,
                 ip_addresses: Optional[Sequence[str]] = None,
                 is_ca: Optional[bool] = None,
                 keystores: Optional['outputs.CertificateSpecKeystores'] = None,
                 private_key: Optional['outputs.CertificateSpecPrivateKey'] = None,
                 renew_before: Optional[str] = None,
                 revision_history_limit: Optional[int] = None,
                 subject: Optional['outputs.CertificateSpecSubject'] = None,
                 uris: Optional[Sequence[str]] = None,
                 usages: Optional[Sequence[str]] = None):
        """
        Desired state of the Certificate resource.
        :param 'CertificateSpecIssuerRefArgs' issuer_ref: IssuerRef is a reference to the issuer for this certificate. If the `kind` field is not set, or set to `Issuer`, an Issuer resource with the given name in the same namespace as the Certificate will be used. If the `kind` field is set to `ClusterIssuer`, a ClusterIssuer with the provided name will be used. The `name` field in this stanza is required at all times.
        :param str secret_name: SecretName is the name of the secret resource that will be automatically created and managed by this Certificate resource. It will be populated with a private key and certificate, signed by the denoted issuer.
        :param str common_name: CommonName is a common name to be used on the Certificate. The CommonName should have a length of 64 characters or fewer to avoid generating invalid CSRs. This value is ignored by TLS clients when any subject alt name is set. This is x509 behaviour: https://tools.ietf.org/html/rfc6125#section-6.4.4
        :param Sequence[str] dns_names: DNSNames is a list of DNS subjectAltNames to be set on the Certificate.
        :param str duration: The requested 'duration' (i.e. lifetime) of the Certificate. This option may be ignored/overridden by some issuer types. If unset this defaults to 90 days. If overridden and `renewBefore` is greater than the actual certificate duration, the certificate will be automatically renewed 2/3rds of the way through the certificate's duration.
        :param Sequence[str] email_addresses: EmailAddresses is a list of email subjectAltNames to be set on the Certificate.
        :param bool encode_usages_in_request: EncodeUsagesInRequest controls whether key usages should be present in the CertificateRequest
        :param Sequence[str] ip_addresses: IPAddresses is a list of IP address subjectAltNames to be set on the Certificate.
        :param bool is_ca: IsCA will mark this Certificate as valid for certificate signing. This will automatically add the `cert sign` usage to the list of `usages`.
        :param 'CertificateSpecKeystoresArgs' keystores: Keystores configures additional keystore output formats stored in the `secretName` Secret resource.
        :param 'CertificateSpecPrivateKeyArgs' private_key: Options to control private keys used for the Certificate.
        :param str renew_before: The amount of time before the currently issued certificate's `notAfter` time that cert-manager will begin to attempt to renew the certificate. If unset this defaults to 30 days. If this value is greater than the total duration of the certificate (i.e. notAfter - notBefore), it will be automatically renewed 2/3rds of the way through the certificate's duration.
        :param int revision_history_limit: revisionHistoryLimit is the maximum number of CertificateRequest revisions that are maintained in the Certificate's history. Each revision represents a single `CertificateRequest` created by this Certificate, either when it was created, renewed, or Spec was changed. Revisions will be removed by oldest first if the number of revisions exceeds this number. If set, revisionHistoryLimit must be a value of `1` or greater. If unset (`nil`), revisions will not be garbage collected. Default value is `nil`.
        :param 'CertificateSpecSubjectArgs' subject: Full X509 name specification (https://golang.org/pkg/crypto/x509/pkix/#Name).
        :param Sequence[str] uris: URIs is a list of URI subjectAltNames to be set on the Certificate.
        :param Sequence[str] usages: Usages is the set of x509 usages that are requested for the certificate. Defaults to `digital signature` and `key encipherment` if not specified.
        """
        pulumi.set(__self__, "issuer_ref", issuer_ref)
        pulumi.set(__self__, "secret_name", secret_name)
        if common_name is not None:
            pulumi.set(__self__, "common_name", common_name)
        if dns_names is not None:
            pulumi.set(__self__, "dns_names", dns_names)
        if duration is not None:
            pulumi.set(__self__, "duration", duration)
        if email_addresses is not None:
            pulumi.set(__self__, "email_addresses", email_addresses)
        if encode_usages_in_request is not None:
            pulumi.set(__self__, "encode_usages_in_request", encode_usages_in_request)
        if ip_addresses is not None:
            pulumi.set(__self__, "ip_addresses", ip_addresses)
        if is_ca is not None:
            pulumi.set(__self__, "is_ca", is_ca)
        if keystores is not None:
            pulumi.set(__self__, "keystores", keystores)
        if private_key is not None:
            pulumi.set(__self__, "private_key", private_key)
        if renew_before is not None:
            pulumi.set(__self__, "renew_before", renew_before)
        if revision_history_limit is not None:
            pulumi.set(__self__, "revision_history_limit", revision_history_limit)
        if subject is not None:
            pulumi.set(__self__, "subject", subject)
        if uris is not None:
            pulumi.set(__self__, "uris", uris)
        if usages is not None:
            pulumi.set(__self__, "usages", usages)

    @property
    @pulumi.getter(name="issuerRef")
    def issuer_ref(self) -> 'outputs.CertificateSpecIssuerRef':
        """
        IssuerRef is a reference to the issuer for this certificate. If the `kind` field is not set, or set to `Issuer`, an Issuer resource with the given name in the same namespace as the Certificate will be used. If the `kind` field is set to `ClusterIssuer`, a ClusterIssuer with the provided name will be used. The `name` field in this stanza is required at all times.
        """
        return pulumi.get(self, "issuer_ref")

    @property
    @pulumi.getter(name="secretName")
    def secret_name(self) -> str:
        """
        SecretName is the name of the secret resource that will be automatically created and managed by this Certificate resource. It will be populated with a private key and certificate, signed by the denoted issuer.
        """
        return pulumi.get(self, "secret_name")

    @property
    @pulumi.getter(name="commonName")
    def common_name(self) -> Optional[str]:
        """
        CommonName is a common name to be used on the Certificate. The CommonName should have a length of 64 characters or fewer to avoid generating invalid CSRs. This value is ignored by TLS clients when any subject alt name is set. This is x509 behaviour: https://tools.ietf.org/html/rfc6125#section-6.4.4
        """
        return pulumi.get(self, "common_name")

    @property
    @pulumi.getter(name="dnsNames")
    def dns_names(self) -> Optional[Sequence[str]]:
        """
        DNSNames is a list of DNS subjectAltNames to be set on the Certificate.
        """
        return pulumi.get(self, "dns_names")

    @property
    @pulumi.getter
    def duration(self) -> Optional[str]:
        """
        The requested 'duration' (i.e. lifetime) of the Certificate. This option may be ignored/overridden by some issuer types. If unset this defaults to 90 days. If overridden and `renewBefore` is greater than the actual certificate duration, the certificate will be automatically renewed 2/3rds of the way through the certificate's duration.
        """
        return pulumi.get(self, "duration")

    @property
    @pulumi.getter(name="emailAddresses")
    def email_addresses(self) -> Optional[Sequence[str]]:
        """
        EmailAddresses is a list of email subjectAltNames to be set on the Certificate.
        """
        return pulumi.get(self, "email_addresses")

    @property
    @pulumi.getter(name="encodeUsagesInRequest")
    def encode_usages_in_request(self) -> Optional[bool]:
        """
        EncodeUsagesInRequest controls whether key usages should be present in the CertificateRequest
        """
        return pulumi.get(self, "encode_usages_in_request")

    @property
    @pulumi.getter(name="ipAddresses")
    def ip_addresses(self) -> Optional[Sequence[str]]:
        """
        IPAddresses is a list of IP address subjectAltNames to be set on the Certificate.
        """
        return pulumi.get(self, "ip_addresses")

    @property
    @pulumi.getter(name="isCA")
    def is_ca(self) -> Optional[bool]:
        """
        IsCA will mark this Certificate as valid for certificate signing. This will automatically add the `cert sign` usage to the list of `usages`.
        """
        return pulumi.get(self, "is_ca")

    @property
    @pulumi.getter
    def keystores(self) -> Optional['outputs.CertificateSpecKeystores']:
        """
        Keystores configures additional keystore output formats stored in the `secretName` Secret resource.
        """
        return pulumi.get(self, "keystores")

    @property
    @pulumi.getter(name="privateKey")
    def private_key(self) -> Optional['outputs.CertificateSpecPrivateKey']:
        """
        Options to control private keys used for the Certificate.
        """
        return pulumi.get(self, "private_key")

    @property
    @pulumi.getter(name="renewBefore")
    def renew_before(self) -> Optional[str]:
        """
        The amount of time before the currently issued certificate's `notAfter` time that cert-manager will begin to attempt to renew the certificate. If unset this defaults to 30 days. If this value is greater than the total duration of the certificate (i.e. notAfter - notBefore), it will be automatically renewed 2/3rds of the way through the certificate's duration.
        """
        return pulumi.get(self, "renew_before")

    @property
    @pulumi.getter(name="revisionHistoryLimit")
    def revision_history_limit(self) -> Optional[int]:
        """
        revisionHistoryLimit is the maximum number of CertificateRequest revisions that are maintained in the Certificate's history. Each revision represents a single `CertificateRequest` created by this Certificate, either when it was created, renewed, or Spec was changed. Revisions will be removed by oldest first if the number of revisions exceeds this number. If set, revisionHistoryLimit must be a value of `1` or greater. If unset (`nil`), revisions will not be garbage collected. Default value is `nil`.
        """
        return pulumi.get(self, "revision_history_limit")

    @property
    @pulumi.getter
    def subject(self) -> Optional['outputs.CertificateSpecSubject']:
        """
        Full X509 name specification (https://golang.org/pkg/crypto/x509/pkix/#Name).
        """
        return pulumi.get(self, "subject")

    @property
    @pulumi.getter
    def uris(self) -> Optional[Sequence[str]]:
        """
        URIs is a list of URI subjectAltNames to be set on the Certificate.
        """
        return pulumi.get(self, "uris")

    @property
    @pulumi.getter
    def usages(self) -> Optional[Sequence[str]]:
        """
        Usages is the set of x509 usages that are requested for the certificate. Defaults to `digital signature` and `key encipherment` if not specified.
        """
        return pulumi.get(self, "usages")

    def _translate_property(self, prop):
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop


@pulumi.output_type
class CertificateSpecIssuerRef(dict):
    """
    IssuerRef is a reference to the issuer for this certificate. If the `kind` field is not set, or set to `Issuer`, an Issuer resource with the given name in the same namespace as the Certificate will be used. If the `kind` field is set to `ClusterIssuer`, a ClusterIssuer with the provided name will be used. The `name` field in this stanza is required at all times.
    """
    def __init__(__self__, *,
                 name: str,
                 group: Optional[str] = None,
                 kind: Optional[str] = None):
        """
        IssuerRef is a reference to the issuer for this certificate. If the `kind` field is not set, or set to `Issuer`, an Issuer resource with the given name in the same namespace as the Certificate will be used. If the `kind` field is set to `ClusterIssuer`, a ClusterIssuer with the provided name will be used. The `name` field in this stanza is required at all times.
        :param str name: Name of the resource being referred to.
        :param str group: Group of the resource being referred to.
        :param str kind: Kind of the resource being referred to.
        """
        pulumi.set(__self__, "name", name)
        if group is not None:
            pulumi.set(__self__, "group", group)
        if kind is not None:
            pulumi.set(__self__, "kind", kind)

    @property
    @pulumi.getter
    def name(self) -> str:
        """
        Name of the resource being referred to.
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def group(self) -> Optional[str]:
        """
        Group of the resource being referred to.
        """
        return pulumi.get(self, "group")

    @property
    @pulumi.getter
    def kind(self) -> Optional[str]:
        """
        Kind of the resource being referred to.
        """
        return pulumi.get(self, "kind")

    def _translate_property(self, prop):
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop


@pulumi.output_type
class CertificateSpecKeystores(dict):
    """
    Keystores configures additional keystore output formats stored in the `secretName` Secret resource.
    """
    def __init__(__self__, *,
                 jks: Optional['outputs.CertificateSpecKeystoresJks'] = None,
                 pkcs12: Optional['outputs.CertificateSpecKeystoresPkcs12'] = None):
        """
        Keystores configures additional keystore output formats stored in the `secretName` Secret resource.
        :param 'CertificateSpecKeystoresJksArgs' jks: JKS configures options for storing a JKS keystore in the `spec.secretName` Secret resource.
        :param 'CertificateSpecKeystoresPkcs12Args' pkcs12: PKCS12 configures options for storing a PKCS12 keystore in the `spec.secretName` Secret resource.
        """
        if jks is not None:
            pulumi.set(__self__, "jks", jks)
        if pkcs12 is not None:
            pulumi.set(__self__, "pkcs12", pkcs12)

    @property
    @pulumi.getter
    def jks(self) -> Optional['outputs.CertificateSpecKeystoresJks']:
        """
        JKS configures options for storing a JKS keystore in the `spec.secretName` Secret resource.
        """
        return pulumi.get(self, "jks")

    @property
    @pulumi.getter
    def pkcs12(self) -> Optional['outputs.CertificateSpecKeystoresPkcs12']:
        """
        PKCS12 configures options for storing a PKCS12 keystore in the `spec.secretName` Secret resource.
        """
        return pulumi.get(self, "pkcs12")

    def _translate_property(self, prop):
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop


@pulumi.output_type
class CertificateSpecKeystoresJks(dict):
    """
    JKS configures options for storing a JKS keystore in the `spec.secretName` Secret resource.
    """
    def __init__(__self__, *,
                 create: bool,
                 password_secret_ref: 'outputs.CertificateSpecKeystoresJksPasswordSecretRef'):
        """
        JKS configures options for storing a JKS keystore in the `spec.secretName` Secret resource.
        :param bool create: Create enables JKS keystore creation for the Certificate. If true, a file named `keystore.jks` will be created in the target Secret resource, encrypted using the password stored in `passwordSecretRef`. The keystore file will only be updated upon re-issuance. A file named `truststore.jks` will also be created in the target Secret resource, encrypted using the password stored in `passwordSecretRef` containing the issuing Certificate Authority
        :param 'CertificateSpecKeystoresJksPasswordSecretRefArgs' password_secret_ref: PasswordSecretRef is a reference to a key in a Secret resource containing the password used to encrypt the JKS keystore.
        """
        pulumi.set(__self__, "create", create)
        pulumi.set(__self__, "password_secret_ref", password_secret_ref)

    @property
    @pulumi.getter
    def create(self) -> bool:
        """
        Create enables JKS keystore creation for the Certificate. If true, a file named `keystore.jks` will be created in the target Secret resource, encrypted using the password stored in `passwordSecretRef`. The keystore file will only be updated upon re-issuance. A file named `truststore.jks` will also be created in the target Secret resource, encrypted using the password stored in `passwordSecretRef` containing the issuing Certificate Authority
        """
        return pulumi.get(self, "create")

    @property
    @pulumi.getter(name="passwordSecretRef")
    def password_secret_ref(self) -> 'outputs.CertificateSpecKeystoresJksPasswordSecretRef':
        """
        PasswordSecretRef is a reference to a key in a Secret resource containing the password used to encrypt the JKS keystore.
        """
        return pulumi.get(self, "password_secret_ref")

    def _translate_property(self, prop):
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop


@pulumi.output_type
class CertificateSpecKeystoresJksPasswordSecretRef(dict):
    """
    PasswordSecretRef is a reference to a key in a Secret resource containing the password used to encrypt the JKS keystore.
    """
    def __init__(__self__, *,
                 name: str,
                 key: Optional[str] = None):
        """
        PasswordSecretRef is a reference to a key in a Secret resource containing the password used to encrypt the JKS keystore.
        :param str name: Name of the resource being referred to. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
        :param str key: The key of the entry in the Secret resource's `data` field to be used. Some instances of this field may be defaulted, in others it may be required.
        """
        pulumi.set(__self__, "name", name)
        if key is not None:
            pulumi.set(__self__, "key", key)

    @property
    @pulumi.getter
    def name(self) -> str:
        """
        Name of the resource being referred to. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def key(self) -> Optional[str]:
        """
        The key of the entry in the Secret resource's `data` field to be used. Some instances of this field may be defaulted, in others it may be required.
        """
        return pulumi.get(self, "key")

    def _translate_property(self, prop):
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop


@pulumi.output_type
class CertificateSpecKeystoresPkcs12(dict):
    """
    PKCS12 configures options for storing a PKCS12 keystore in the `spec.secretName` Secret resource.
    """
    def __init__(__self__, *,
                 create: bool,
                 password_secret_ref: 'outputs.CertificateSpecKeystoresPkcs12PasswordSecretRef'):
        """
        PKCS12 configures options for storing a PKCS12 keystore in the `spec.secretName` Secret resource.
        :param bool create: Create enables PKCS12 keystore creation for the Certificate. If true, a file named `keystore.p12` will be created in the target Secret resource, encrypted using the password stored in `passwordSecretRef`. The keystore file will only be updated upon re-issuance. A file named `truststore.p12` will also be created in the target Secret resource, encrypted using the password stored in `passwordSecretRef` containing the issuing Certificate Authority
        :param 'CertificateSpecKeystoresPkcs12PasswordSecretRefArgs' password_secret_ref: PasswordSecretRef is a reference to a key in a Secret resource containing the password used to encrypt the PKCS12 keystore.
        """
        pulumi.set(__self__, "create", create)
        pulumi.set(__self__, "password_secret_ref", password_secret_ref)

    @property
    @pulumi.getter
    def create(self) -> bool:
        """
        Create enables PKCS12 keystore creation for the Certificate. If true, a file named `keystore.p12` will be created in the target Secret resource, encrypted using the password stored in `passwordSecretRef`. The keystore file will only be updated upon re-issuance. A file named `truststore.p12` will also be created in the target Secret resource, encrypted using the password stored in `passwordSecretRef` containing the issuing Certificate Authority
        """
        return pulumi.get(self, "create")

    @property
    @pulumi.getter(name="passwordSecretRef")
    def password_secret_ref(self) -> 'outputs.CertificateSpecKeystoresPkcs12PasswordSecretRef':
        """
        PasswordSecretRef is a reference to a key in a Secret resource containing the password used to encrypt the PKCS12 keystore.
        """
        return pulumi.get(self, "password_secret_ref")

    def _translate_property(self, prop):
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop


@pulumi.output_type
class CertificateSpecKeystoresPkcs12PasswordSecretRef(dict):
    """
    PasswordSecretRef is a reference to a key in a Secret resource containing the password used to encrypt the PKCS12 keystore.
    """
    def __init__(__self__, *,
                 name: str,
                 key: Optional[str] = None):
        """
        PasswordSecretRef is a reference to a key in a Secret resource containing the password used to encrypt the PKCS12 keystore.
        :param str name: Name of the resource being referred to. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
        :param str key: The key of the entry in the Secret resource's `data` field to be used. Some instances of this field may be defaulted, in others it may be required.
        """
        pulumi.set(__self__, "name", name)
        if key is not None:
            pulumi.set(__self__, "key", key)

    @property
    @pulumi.getter
    def name(self) -> str:
        """
        Name of the resource being referred to. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def key(self) -> Optional[str]:
        """
        The key of the entry in the Secret resource's `data` field to be used. Some instances of this field may be defaulted, in others it may be required.
        """
        return pulumi.get(self, "key")

    def _translate_property(self, prop):
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop


@pulumi.output_type
class CertificateSpecPrivateKey(dict):
    """
    Options to control private keys used for the Certificate.
    """
    def __init__(__self__, *,
                 algorithm: Optional[str] = None,
                 encoding: Optional[str] = None,
                 rotation_policy: Optional[str] = None,
                 size: Optional[int] = None):
        """
        Options to control private keys used for the Certificate.
        :param str algorithm: Algorithm is the private key algorithm of the corresponding private key for this certificate. If provided, allowed values are either `RSA` or `ECDSA` If `algorithm` is specified and `size` is not provided, key size of 256 will be used for `ECDSA` key algorithm and key size of 2048 will be used for `RSA` key algorithm.
        :param str encoding: The private key cryptography standards (PKCS) encoding for this certificate's private key to be encoded in. If provided, allowed values are `PKCS1` and `PKCS8` standing for PKCS#1 and PKCS#8, respectively. Defaults to `PKCS1` if not specified.
        :param str rotation_policy: RotationPolicy controls how private keys should be regenerated when a re-issuance is being processed. If set to Never, a private key will only be generated if one does not already exist in the target `spec.secretName`. If one does exists but it does not have the correct algorithm or size, a warning will be raised to await user intervention. If set to Always, a private key matching the specified requirements will be generated whenever a re-issuance occurs. Default is 'Never' for backward compatibility.
        :param int size: Size is the key bit size of the corresponding private key for this certificate. If `algorithm` is set to `RSA`, valid values are `2048`, `4096` or `8192`, and will default to `2048` if not specified. If `algorithm` is set to `ECDSA`, valid values are `256`, `384` or `521`, and will default to `256` if not specified. No other values are allowed.
        """
        if algorithm is not None:
            pulumi.set(__self__, "algorithm", algorithm)
        if encoding is not None:
            pulumi.set(__self__, "encoding", encoding)
        if rotation_policy is not None:
            pulumi.set(__self__, "rotation_policy", rotation_policy)
        if size is not None:
            pulumi.set(__self__, "size", size)

    @property
    @pulumi.getter
    def algorithm(self) -> Optional[str]:
        """
        Algorithm is the private key algorithm of the corresponding private key for this certificate. If provided, allowed values are either `RSA` or `ECDSA` If `algorithm` is specified and `size` is not provided, key size of 256 will be used for `ECDSA` key algorithm and key size of 2048 will be used for `RSA` key algorithm.
        """
        return pulumi.get(self, "algorithm")

    @property
    @pulumi.getter
    def encoding(self) -> Optional[str]:
        """
        The private key cryptography standards (PKCS) encoding for this certificate's private key to be encoded in. If provided, allowed values are `PKCS1` and `PKCS8` standing for PKCS#1 and PKCS#8, respectively. Defaults to `PKCS1` if not specified.
        """
        return pulumi.get(self, "encoding")

    @property
    @pulumi.getter(name="rotationPolicy")
    def rotation_policy(self) -> Optional[str]:
        """
        RotationPolicy controls how private keys should be regenerated when a re-issuance is being processed. If set to Never, a private key will only be generated if one does not already exist in the target `spec.secretName`. If one does exists but it does not have the correct algorithm or size, a warning will be raised to await user intervention. If set to Always, a private key matching the specified requirements will be generated whenever a re-issuance occurs. Default is 'Never' for backward compatibility.
        """
        return pulumi.get(self, "rotation_policy")

    @property
    @pulumi.getter
    def size(self) -> Optional[int]:
        """
        Size is the key bit size of the corresponding private key for this certificate. If `algorithm` is set to `RSA`, valid values are `2048`, `4096` or `8192`, and will default to `2048` if not specified. If `algorithm` is set to `ECDSA`, valid values are `256`, `384` or `521`, and will default to `256` if not specified. No other values are allowed.
        """
        return pulumi.get(self, "size")

    def _translate_property(self, prop):
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop


@pulumi.output_type
class CertificateSpecSubject(dict):
    """
    Full X509 name specification (https://golang.org/pkg/crypto/x509/pkix/#Name).
    """
    def __init__(__self__, *,
                 countries: Optional[Sequence[str]] = None,
                 localities: Optional[Sequence[str]] = None,
                 organizational_units: Optional[Sequence[str]] = None,
                 organizations: Optional[Sequence[str]] = None,
                 postal_codes: Optional[Sequence[str]] = None,
                 provinces: Optional[Sequence[str]] = None,
                 serial_number: Optional[str] = None,
                 street_addresses: Optional[Sequence[str]] = None):
        """
        Full X509 name specification (https://golang.org/pkg/crypto/x509/pkix/#Name).
        :param Sequence[str] countries: Countries to be used on the Certificate.
        :param Sequence[str] localities: Cities to be used on the Certificate.
        :param Sequence[str] organizational_units: Organizational Units to be used on the Certificate.
        :param Sequence[str] organizations: Organizations to be used on the Certificate.
        :param Sequence[str] postal_codes: Postal codes to be used on the Certificate.
        :param Sequence[str] provinces: State/Provinces to be used on the Certificate.
        :param str serial_number: Serial number to be used on the Certificate.
        :param Sequence[str] street_addresses: Street addresses to be used on the Certificate.
        """
        if countries is not None:
            pulumi.set(__self__, "countries", countries)
        if localities is not None:
            pulumi.set(__self__, "localities", localities)
        if organizational_units is not None:
            pulumi.set(__self__, "organizational_units", organizational_units)
        if organizations is not None:
            pulumi.set(__self__, "organizations", organizations)
        if postal_codes is not None:
            pulumi.set(__self__, "postal_codes", postal_codes)
        if provinces is not None:
            pulumi.set(__self__, "provinces", provinces)
        if serial_number is not None:
            pulumi.set(__self__, "serial_number", serial_number)
        if street_addresses is not None:
            pulumi.set(__self__, "street_addresses", street_addresses)

    @property
    @pulumi.getter
    def countries(self) -> Optional[Sequence[str]]:
        """
        Countries to be used on the Certificate.
        """
        return pulumi.get(self, "countries")

    @property
    @pulumi.getter
    def localities(self) -> Optional[Sequence[str]]:
        """
        Cities to be used on the Certificate.
        """
        return pulumi.get(self, "localities")

    @property
    @pulumi.getter(name="organizationalUnits")
    def organizational_units(self) -> Optional[Sequence[str]]:
        """
        Organizational Units to be used on the Certificate.
        """
        return pulumi.get(self, "organizational_units")

    @property
    @pulumi.getter
    def organizations(self) -> Optional[Sequence[str]]:
        """
        Organizations to be used on the Certificate.
        """
        return pulumi.get(self, "organizations")

    @property
    @pulumi.getter(name="postalCodes")
    def postal_codes(self) -> Optional[Sequence[str]]:
        """
        Postal codes to be used on the Certificate.
        """
        return pulumi.get(self, "postal_codes")

    @property
    @pulumi.getter
    def provinces(self) -> Optional[Sequence[str]]:
        """
        State/Provinces to be used on the Certificate.
        """
        return pulumi.get(self, "provinces")

    @property
    @pulumi.getter(name="serialNumber")
    def serial_number(self) -> Optional[str]:
        """
        Serial number to be used on the Certificate.
        """
        return pulumi.get(self, "serial_number")

    @property
    @pulumi.getter(name="streetAddresses")
    def street_addresses(self) -> Optional[Sequence[str]]:
        """
        Street addresses to be used on the Certificate.
        """
        return pulumi.get(self, "street_addresses")

    def _translate_property(self, prop):
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop


@pulumi.output_type
class CertificateStatus(dict):
    """
    Status of the Certificate. This is set and managed automatically.
    """
    def __init__(__self__, *,
                 conditions: Optional[Sequence['outputs.CertificateStatusConditions']] = None,
                 last_failure_time: Optional[str] = None,
                 next_private_key_secret_name: Optional[str] = None,
                 not_after: Optional[str] = None,
                 not_before: Optional[str] = None,
                 renewal_time: Optional[str] = None,
                 revision: Optional[int] = None):
        """
        Status of the Certificate. This is set and managed automatically.
        :param Sequence['CertificateStatusConditionsArgs'] conditions: List of status conditions to indicate the status of certificates. Known condition types are `Ready` and `Issuing`.
        :param str last_failure_time: LastFailureTime is the time as recorded by the Certificate controller of the most recent failure to complete a CertificateRequest for this Certificate resource. If set, cert-manager will not re-request another Certificate until 1 hour has elapsed from this time.
        :param str next_private_key_secret_name: The name of the Secret resource containing the private key to be used for the next certificate iteration. The keymanager controller will automatically set this field if the `Issuing` condition is set to `True`. It will automatically unset this field when the Issuing condition is not set or False.
        :param str not_after: The expiration time of the certificate stored in the secret named by this resource in `spec.secretName`.
        :param str not_before: The time after which the certificate stored in the secret named by this resource in spec.secretName is valid.
        :param str renewal_time: RenewalTime is the time at which the certificate will be next renewed. If not set, no upcoming renewal is scheduled.
        :param int revision: The current 'revision' of the certificate as issued. 
                When a CertificateRequest resource is created, it will have the `cert-manager.io/certificate-revision` set to one greater than the current value of this field. 
                Upon issuance, this field will be set to the value of the annotation on the CertificateRequest resource used to issue the certificate. 
                Persisting the value on the CertificateRequest resource allows the certificates controller to know whether a request is part of an old issuance or if it is part of the ongoing revision's issuance by checking if the revision value in the annotation is greater than this field.
        """
        if conditions is not None:
            pulumi.set(__self__, "conditions", conditions)
        if last_failure_time is not None:
            pulumi.set(__self__, "last_failure_time", last_failure_time)
        if next_private_key_secret_name is not None:
            pulumi.set(__self__, "next_private_key_secret_name", next_private_key_secret_name)
        if not_after is not None:
            pulumi.set(__self__, "not_after", not_after)
        if not_before is not None:
            pulumi.set(__self__, "not_before", not_before)
        if renewal_time is not None:
            pulumi.set(__self__, "renewal_time", renewal_time)
        if revision is not None:
            pulumi.set(__self__, "revision", revision)

    @property
    @pulumi.getter
    def conditions(self) -> Optional[Sequence['outputs.CertificateStatusConditions']]:
        """
        List of status conditions to indicate the status of certificates. Known condition types are `Ready` and `Issuing`.
        """
        return pulumi.get(self, "conditions")

    @property
    @pulumi.getter(name="lastFailureTime")
    def last_failure_time(self) -> Optional[str]:
        """
        LastFailureTime is the time as recorded by the Certificate controller of the most recent failure to complete a CertificateRequest for this Certificate resource. If set, cert-manager will not re-request another Certificate until 1 hour has elapsed from this time.
        """
        return pulumi.get(self, "last_failure_time")

    @property
    @pulumi.getter(name="nextPrivateKeySecretName")
    def next_private_key_secret_name(self) -> Optional[str]:
        """
        The name of the Secret resource containing the private key to be used for the next certificate iteration. The keymanager controller will automatically set this field if the `Issuing` condition is set to `True`. It will automatically unset this field when the Issuing condition is not set or False.
        """
        return pulumi.get(self, "next_private_key_secret_name")

    @property
    @pulumi.getter(name="notAfter")
    def not_after(self) -> Optional[str]:
        """
        The expiration time of the certificate stored in the secret named by this resource in `spec.secretName`.
        """
        return pulumi.get(self, "not_after")

    @property
    @pulumi.getter(name="notBefore")
    def not_before(self) -> Optional[str]:
        """
        The time after which the certificate stored in the secret named by this resource in spec.secretName is valid.
        """
        return pulumi.get(self, "not_before")

    @property
    @pulumi.getter(name="renewalTime")
    def renewal_time(self) -> Optional[str]:
        """
        RenewalTime is the time at which the certificate will be next renewed. If not set, no upcoming renewal is scheduled.
        """
        return pulumi.get(self, "renewal_time")

    @property
    @pulumi.getter
    def revision(self) -> Optional[int]:
        """
        The current 'revision' of the certificate as issued. 
         When a CertificateRequest resource is created, it will have the `cert-manager.io/certificate-revision` set to one greater than the current value of this field. 
         Upon issuance, this field will be set to the value of the annotation on the CertificateRequest resource used to issue the certificate. 
         Persisting the value on the CertificateRequest resource allows the certificates controller to know whether a request is part of an old issuance or if it is part of the ongoing revision's issuance by checking if the revision value in the annotation is greater than this field.
        """
        return pulumi.get(self, "revision")

    def _translate_property(self, prop):
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop


@pulumi.output_type
class CertificateStatusConditions(dict):
    """
    CertificateCondition contains condition information for an Certificate.
    """
    def __init__(__self__, *,
                 status: str,
                 type: str,
                 last_transition_time: Optional[str] = None,
                 message: Optional[str] = None,
                 observed_generation: Optional[int] = None,
                 reason: Optional[str] = None):
        """
        CertificateCondition contains condition information for an Certificate.
        :param str status: Status of the condition, one of (`True`, `False`, `Unknown`).
        :param str type: Type of the condition, known values are (`Ready`, `Issuing`).
        :param str last_transition_time: LastTransitionTime is the timestamp corresponding to the last status change of this condition.
        :param str message: Message is a human readable description of the details of the last transition, complementing reason.
        :param int observed_generation: If set, this represents the .metadata.generation that the condition was set based upon. For instance, if .metadata.generation is currently 12, but the .status.condition[x].observedGeneration is 9, the condition is out of date with respect to the current state of the Certificate.
        :param str reason: Reason is a brief machine readable explanation for the condition's last transition.
        """
        pulumi.set(__self__, "status", status)
        pulumi.set(__self__, "type", type)
        if last_transition_time is not None:
            pulumi.set(__self__, "last_transition_time", last_transition_time)
        if message is not None:
            pulumi.set(__self__, "message", message)
        if observed_generation is not None:
            pulumi.set(__self__, "observed_generation", observed_generation)
        if reason is not None:
            pulumi.set(__self__, "reason", reason)

    @property
    @pulumi.getter
    def status(self) -> str:
        """
        Status of the condition, one of (`True`, `False`, `Unknown`).
        """
        return pulumi.get(self, "status")

    @property
    @pulumi.getter
    def type(self) -> str:
        """
        Type of the condition, known values are (`Ready`, `Issuing`).
        """
        return pulumi.get(self, "type")

    @property
    @pulumi.getter(name="lastTransitionTime")
    def last_transition_time(self) -> Optional[str]:
        """
        LastTransitionTime is the timestamp corresponding to the last status change of this condition.
        """
        return pulumi.get(self, "last_transition_time")

    @property
    @pulumi.getter
    def message(self) -> Optional[str]:
        """
        Message is a human readable description of the details of the last transition, complementing reason.
        """
        return pulumi.get(self, "message")

    @property
    @pulumi.getter(name="observedGeneration")
    def observed_generation(self) -> Optional[int]:
        """
        If set, this represents the .metadata.generation that the condition was set based upon. For instance, if .metadata.generation is currently 12, but the .status.condition[x].observedGeneration is 9, the condition is out of date with respect to the current state of the Certificate.
        """
        return pulumi.get(self, "observed_generation")

    @property
    @pulumi.getter
    def reason(self) -> Optional[str]:
        """
        Reason is a brief machine readable explanation for the condition's last transition.
        """
        return pulumi.get(self, "reason")

    def _translate_property(self, prop):
        return _tables.CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop


